CREATE TABLE IF NOT EXISTS lerg_codes (
  id SERIAL PRIMARY KEY,
  npa CHARACTER(3) NOT NULL,
  nxx CHARACTER(3) NOT NULL,
  npanxx CHARACTER(6) GENERATED ALWAYS AS (npa || nxx) STORED,
  state CHARACTER(2) NOT NULL,
  last_updated TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT unique_npanxx UNIQUE (npanxx)
);

CREATE INDEX IF NOT EXISTS idx_lerg_npanxx ON lerg_codes(npanxx); 